Feature/authorization
simplegoose/blog_app pull request #10
Opened 2024-01-26 16:30 UTC by simplegoose

In this PR, the following was done:

- Cancan was installed as a dependency for authorization of users.
- The routes were updated to handle delete routes for comments and posts.
- An ability model was generated using cancan to check if a user has the role of admin to perform actions allowed.
- The view was updated with a button to delete a comment or post if a user was authorized.

2024-01-26 17:13 UTC, Munsa1 requested changes
Hi @simplegoose, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Added Authorization Infrastructure :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-26 17:13 UTC, Munsa1 commented on app/controllers/posts_controller.rb
> +
- [ ] Good job implementing the destroy actions in the PostsController and in the CommentsController as requested, however a user is currently unable to create a post and comment, therefore I am unable to check the functionality of the app. Please remember that:

- A user can delete a post if it is theirs or if they have an admin role (column role has value "admin"). Use CanCanCan for this authorization.
For that, you need to implement the `post deleting` functionality. Add the "Delete" button to the view and make sure that only authorized users can see it.
- A user can delete a comment if it is theirs or if they have an admin role (column role has value "admin"). Use CanCanCan for this authorization.
For that, you need to implement the `comment deleting` functionality. Add the "Delete" button to the view and make sure that only authorized users can see it.



VideoCast
[cinnamon-2024-01-26T190439+0200.webm](https://github.com/simplegoose/blog_app/assets/81932478/a2978ec9-0094-423f-a678-2b81820d5583)

2024-01-26 19:06 UTC, LionRouge1 requested changes
Hi @simplegoose, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Suggested changes :recycle: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-26 19:06 UTC, LionRouge1 commented on app/controllers/posts_controller.rb
[Regarding the create action]
- [ ] I also encountered the same challenge as mentioned by the previous reviewer. I'm unable to assess the authorization functionality due to the inability to create a post or comment from your application. Upon investigation, I observed that the **current_user** is nil in your application, resulting in a nil author value and preventing the post or comment from being saved. Please look into this matter.

2024-01-26 19:20 UTC, simplegoose commented on app/controllers/posts_controller.rb
Thank you for the review @LionRouge1. I think the error you are facing is due to logging in. In the previous milestones, we were told to remove the current_user method since it will be provided by devise, so you aren't able to post anything if you are not logged in.

2024-01-27 06:27 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Team,  

**Blog app: add authorization rules** is complete! 🏁 Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 Good job on adding improvement to the app authentication!
🎲 Good ReadMe!

## Optional suggestions 🧰 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

**You can also consider:**
Kindly include details of the other co-contributor(s) in your ReadMe.

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-27 06:28 UTC, merged