Feature/forms
simplegoose/blog_app pull request #7
Opened 2024-01-18 18:44 UTC by simplegoose

In this PR, the following was done:

- New view files for creating posts and comments were created.
- New controllers for likes and comments were created.
- New routes to comments and likes were created.

2024-01-18 19:17 UTC, Efiamotu-1 requested changes
Hi @simplegoose, 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-18 19:17 UTC, Efiamotu-1 commented on app/assets/stylesheets/application.css
- [ ] Your readme file currently has a broken link as shown in the image below, under the `contributing section` the issues link when clicked shows an error  404 page, please kindly fix this :+1: :sparkles: 
![mil](https://github.com/simplegoose/blog_app/assets/89055502/727609d1-6bc9-4c5a-94fc-5fef49af7c22)

2024-01-19 16:07 UTC, simplegoose commented on app/assets/stylesheets/application.css
@Efiamotu-1 The link is working, I don't know why you are getting an error.
![Screenshot (63)](https://github.com/simplegoose/blog_app/assets/77801066/b4dbbdef-f698-43c1-9e2c-6dd239bd04e8)

2024-01-19 18:31 UTC, LionRouge1 requested changes
Hi @simplegoose, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Suggested changes :recycle: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-19 18:31 UTC, LionRouge1 commented on README.md
- [ ] As mentioned by the previous reviewer the issues page link is broken. Kindly update the issues page link to make your project look more professional.

**HIT:** use this [link](https://github.com/simplegoose/blog_app/issues) to link to your repo issues `https://github.com/simplegoose/blog_app/issues`

2024-01-19 18:33 UTC, simplegoose commented on README.md
@LionRouge1, I am using git flow for creating my branches. I don't know how to fix that, please since you have raised an issue once again you could at least suggest what's to be done?

2024-01-19 18:44 UTC, LionRouge1 commented on README.md
@simplegoose, USE THE LINK THAT I SHARE IN THE **HIT** (`https://github.com/simplegoose/blog_app/issues`) INSTEAD OF `https://github.com/simplegoose/blog_app/blob/issues`

2024-01-19 18:45 UTC, LionRouge1 approved these changes
Hi @simplegoose, 

# STATUS: APPROVED! 🥇 💯 
Great work on making the changes 👏 
You've done well implementing the requested changes

![done](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

## Highlights
- Great job, your project is error free :+1: 
- Nice work you meet all the requirements :1st_place_medal: 
- All linters passed :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-19 18:46 UTC, merged